---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aitrigram-ihomeland-cn-v1-llmengine
  failurePolicy: Fail
  name: mllmengine-v1.kb.io
  rules:
  - apiGroups:
    - aitrigram.ihomeland.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llmengines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aitrigram-ihomeland-cn-v1-llmengine
  failurePolicy: Fail
  name: vllmengine-v1.kb.io
  rules:
  - apiGroups:
    - aitrigram.ihomeland.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llmengines
  sideEffects: None
