# This rule is not used by the project aitrigram itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the aitrigram.ihomeland.cn.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: llmengine-editor-role
rules:
- apiGroups:
  - aitrigram.ihomeland.cn
  resources:
  - llmengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aitrigram.ihomeland.cn
  resources:
  - llmengines/status
  verbs:
  - get
