# This rule is not used by the project aitrigram itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to aitrigram.ihomeland.cn resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: llmengine-viewer-role
rules:
- apiGroups:
  - aitrigram.ihomeland.cn
  resources:
  - llmengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aitrigram.ihomeland.cn
  resources:
  - llmengines/status
  verbs:
  - get
