apiVersion: aitrigram.ihomeland.cn/v1
kind: LLMEngine
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: ollama-engine
spec:
  # the docker image for this LLMEngine
  engineType: "ollama"
  replicas: 2
  models:
    - name: "gemma3-1b-with-cpu"
      nameInEngine: "gemma3:1b"
