apiVersion: aitrigram.ihomeland.cn/v1
kind: LLMModel
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: llmmodel-sample
spec:
  # TODO(user): Add fields here
