# with this LLMEngine, there are deployments, pods and service created for it.
# The Ingress service is also created to expose the LLMEngine.
# The Ingress service is exposed on the host k8s-worker and the path /ollama.
apiVersion: aitrigram.ihomeland.cn/v1
kind: LLMEngine
metadata:
  labels:
    app.kubernetes.io/name: aitrigram
    app.kubernetes.io/managed-by: kustomize
  name: ollama-engine
spec:
  # the docker image for this LLMEngine
  engineType: "ollama"
  replicas: 2
---
# ingress service to expose the LLMEngine
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-engine
  annotations:
    # path-rewrite removes the '/ollama' in the path to pass to backend ollama servers.
     haproxy.org/path-rewrite: /ollama/(.*) /\1
  labels:
    name: ollama-engine
spec:
  ingressClassName: haproxy-ingress
  rules:
  - host: k8s-worker
    http:
      paths:
      - pathType: Prefix
        path: /ollama
        backend:
          service:
            name: ollama-engine
            port:
              number: 8080
